import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hello from '../components/Hello';
import NewConcept from "@/components/NewConcept";
import ComponentWrapper from "@/components/ComponentWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
 
            <h1>
            OUR FIRST REACT APP
            </h1>
            <Hello/>
            <ComponentWrapper textColor={"blue"}>
  
              <NewConcept concept={"how to import components"}/>
              <NewConcept concept={"how to use props in a component"} />
              <NewConcept concept={"how children property works"} />
            </ComponentWrapper>
        </main>
      </div>
    </>
  );
}
